ada:
	gnatmake Ada/binarysearch.adb

c:
	gcc -Wall -Wextra C/binarySearch.c -o binarySearchC.out

cpp:
	g++ -Wall -Wextra C++/binarySearch.cpp -o binarySearchCpp.out

java:
	javac Java/BinarySearch.java

clean:
	rm -rf *.out *.o *.ali *.class